name = "mbti-boardgame-api-dev"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "6b0c09e5f370b202dd45b8dc191e2e84"

[[d1_databases]]
binding = "DB"
database_name = "boardgame-dev-db"
database_id = "b20f8252-9040-42c1-b637-ed47cdca6919"
